api_keys:
  openai: 
  pagespeed: 
crawling:
  delay_seconds: 1.0
  max_pages: 100
  respect_robots_txt: true
  timeout_seconds: 30
seo_analysis:
  meta_description:
    max_length: 160
    min_length: 70
  title:
    max_length: 60
    min_length: 30
